{
 "title": "MDDB Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])) by (name) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(name) (container_memory_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage / limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(name) (container_memory_usage_bytes{name!=\"\"} > 0) / avg by(name) (container_spec_memory_limit_bytes{name!=\"\"} > 0)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_fs_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "Free" },
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_free_bytes)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "API stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(route) (rate({service_name=\"rest-api\"} | __error__=`` [$__range])) * 60",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status_code) (count_over_time({service_name=\"rest-api\"} | __error__=`` [$__range]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(requestSource) (count_over_time({service_name=\"rest-api\"} | __error__=`` [$__range]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(host) (count_over_time({service_name=\"rest-api\"} | host != `` | __error__=`` [$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Location count (1 week)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country, region, city) (count_over_time({service_name=\"rest-api\"} | __error__=`` | country != `` [1w]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "404 errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(1, sum by(route, referenceID) (count_over_time({service_name=\"rest-api\"} | status_code = `404` | __error__=`` [$__auto])))"
    }
   ]
  }
 ]
}