{
 "title": "MDDB Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Node up",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_http_status_code / 200", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[10m])) by (name) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_fs_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(name) (container_memory_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage / limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(name) (container_memory_usage_bytes{name!=\"\"} > 0) / avg by(name) (container_spec_memory_limit_bytes{name!=\"\"} > 0)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "Free" },
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(device) (node_filesystem_size_bytes{device!=\"none\"}) - (sum by(device) (node_filesystem_free_bytes))) / (sum by(device) (node_filesystem_size_bytes))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "API stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(route) (rate({service_name=\"rest-api\"} | route !~ `.*\\d.*` | __error__=`` [1h])) * 60",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(sum by(status_code) (rate({service_name=\"rest-api\"} | __error__=`` [1h]))) * 60",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source) (rate({service_name=\"rest-api\"} | __error__=`` | label_format source=requestSource [1h])) * 60",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(host) (rate({service_name=\"rest-api\"} | host != `` | host != `localhost` | __error__=`` [1h])) * 60",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country) (rate({service_name=\"rest-api\"} | __error__=`` [1h])) * 60",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Country",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country) (count_over_time({service_name=\"rest-api\"} | __error__=`` | country != `` [$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Location",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country, region, city) (count_over_time({service_name=\"rest-api\"} | __error__=`` | country != `` [$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "404 errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(1, sum by(route, referenceID) (count_over_time({service_name=\"rest-api\"} | status_code = `404` | __error__=`` [$__auto])))"
    }
   ]
  },
  {
   "title": "Top 10 accesions",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(accession) (count_over_time({service_name=\"rest-api\"} | accession != `` [$__range])))"
    }
   ]
  }
 ]
}