services:
  apache:
    build:
      args:
        MCP_INNER_PORT: ${MCP_INNER_PORT}
        
  mcp:
    image: mcp_image
    build:
      context: ./mcp   # folder to search Dockerfile for this image
      args:
        MCP_INNER_PORT: ${MCP_INNER_PORT}   # Build argument for the inner port
        MCP_ROOT_PATH: ${MCP_ROOT_PATH}   # Build argument for the root path
        REST_INNER_PORT: ${REST_INNER_PORT}   # Build argument for the REST API inner port
        MCP_DB_NAME: ${MCP_DB_NAME}   # Build argument for the MongoDB database name
        CLIENT_URL: ${MINIO_PROTOCOL}:\/\/${MINIO_URL}   # Build argument for the client URL
        MCP_ACCESSION: ${MCP_ACCESSION}   # Build argument for the MCP accession URL
    depends_on:
      - mongodb
    volumes:
      - ./swagger.json:/data/swagger.json   # path to Swagger JSON file
    ports:
      - "${MCP_OUTER_PORT}:${MCP_INNER_PORT}"   # port mapping
    networks:
      - web_network
    deploy:
      replicas: ${MCP_REPLICAS}   # Specify the number of replicas for Docker Swarm
      resources:
        limits:
          cpus: ${MCP_CPU_LIMIT}   # Specify the limit number of CPUs
          memory: ${MCP_MEMORY_LIMIT}   # Specify the limit memory
        reservations:
          cpus: ${MCP_CPU_RESERVATION}   # Specify the reserved number of CPUs
          memory: ${MCP_MEMORY_RESERVATION}   # Specify the reserved memory
      restart_policy:
        condition: any   # Restart always
      update_config:
        order: start-first  # Priority over other services