services:
  apache:
    build:
      args:
        OPTIMADE_INNER_PORT: ${OPTIMADE_INNER_PORT}
        
  optimade:
    image: optimade_image
    build:
      context: ./optimade   # folder to search Dockerfile for this image
      args:
        DB_SERVER: ${DB_SERVER}
        DB_PORT: ${DB_OUTER_PORT}
        DB_NAME: ${DB_NAME}
        DB_AUTH_USER: ${REST_DB_LOGIN}
        DB_AUTH_PASSWORD: ${REST_DB_PASSWORD}
        DB_AUTHSOURCE: ${DB_AUTHSOURCE}
        PROTOCOL: ${MINIO_PROTOCOL}
        URL: ${MINIO_URL}
        OPTIMADE_INNER_PORT: ${OPTIMADE_INNER_PORT}
    depends_on:
      - mongodb
    ports:
      - "${OPTIMADE_OUTER_PORT}:${OPTIMADE_INNER_PORT}"   # port mapping
    networks:
      - web_network
    deploy:
      replicas: ${OPTIMADE_REPLICAS}   # Specify the number of replicas for Docker Swarm
      resources:
        limits:
          cpus: ${OPTIMADE_CPU_LIMIT}   # Specify the limit number of CPUs
          memory: ${OPTIMADE_MEMORY_LIMIT}   # Specify the limit memory
        reservations:
          cpus: ${OPTIMADE_CPU_RESERVATION}   # Specify the reserved number of CPUs
          memory: ${OPTIMADE_MEMORY_RESERVATION}   # Specify the reserved memory
      restart_policy:
        condition: any   # Restart always
      update_config:
        order: start-first  # Priority over other services