{
 "title": "MDDB Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])) by (name) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(name) (container_memory_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_free_bytes)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Container size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (container_fs_usage_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total"
    },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "Free" },
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Route sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(route) (count_over_time({app=\"rest-api\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}